<a href="https://colab.research.google.com/github/Anantmishra1907/phythonlearning/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install numpy

In [2]:
import numpy as np

In [3]:
print(np.__version__)


2.0.2


In [4]:
a = np.array([1 , 2 , 3, 4 ,5 ,6 ])
print(a)


[1 2 3 4 5 6]


In [5]:
a[0] = 10
print(a)


[10  2  3  4  5  6]


In [7]:
a[2:]
print(a);


[10  2  3  4  5  6]


# Array attributes

In [8]:
a.ndim

1

In [10]:
a.shape

(6,)

In [11]:
a.size

6

In [12]:
a.dtype

dtype('int64')

#How to create a basic array

In [13]:
np.zeros(4)

array([0., 0., 0., 0.])

In [15]:
np.ones((2 , 6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [16]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [19]:
np.arange(2 , 9 , 2)

array([2, 4, 6, 8])

#Adding, removing, and sorting elements

In [20]:
arr = np.array([2 , 1 , 5 , 3 , 7 , 4 , 6 , 8])

In [21]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [22]:
c = np.array([1 , 2 , 3 , 4])
d = np.array([5 , 6 , 7 , 8])

In [23]:
np.concatenate((c , d))


array([1, 2, 3, 4, 5, 6, 7, 8])

In [24]:
e = c.reshape((2 , 2))
f = d.reshape((2 , 2))

In [25]:
print(e)

[[1 2]
 [3 4]]


# Basic Array Opperation

In [26]:
data = np.array([1 , 2])
ones = np.ones(2 , dtype=np.int_)
data+ones

array([2, 3])

In [27]:
c.sum()

np.int64(10)

In [28]:
c.max()

np.int64(4)

In [29]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [30]:
np.unique(a)

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [31]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [33]:
reveerse = np.flip(arr)
print(reveerse)

[8 7 6 5 4 3 2 1]
